name: dart_express
description: A express-like HTTP framework built in Dart
version: 1.0.0
homepage: https://www.example.com
author: Devin Riegle <riegledevin@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  http: any
  meta: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
