name: dart_express
description: A express-like HTTP framework built in Dart
version: 0.1.0
homepage: https://github.com/deriegle/dart-express
author: Devin Riegle <riegledevin@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  path: any
  http: any
  meta: any
  jael: any
  mustache4dart: any

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
