name: dart_express
description: A express-like HTTP framework built in Dart
version: 0.1.1
homepage: https://github.com/deriegle/dart-express
author: Devin Riegle <riegledevin@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  path: ^1.6.4
  file: ^5.0.0
  http: ^0.12.0+2
  meta: ^1.1.7
  jael: ^2.0.2
  jael_preprocessor: ^2.0.0
  mustache4dart: ^3.0.0-dev.0.0
  code_buffer: ^1.0.1
  symbol_table: ^2.0.0

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.0
